terraform {
  cloud {
    organization = "SAMEER_snowflake"

    workspaces {
      name = "databricks-prod"
    }
  }

  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.50"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "databricks" {
  host  = var.databricks_host
  token = var.databricks_token
}

provider "aws" {
  region     = var.aws_region
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key
}

# --- S3 folder for catalog storage ---
resource "aws_s3_object" "catalog_folder" {
  bucket  = var.s3_bucket_name
  key     = "databricks-catalog/"
  content = ""
}

# --- IAM Role for Databricks to access S3 ---
resource "aws_iam_role" "databricks_role" {
  name = var.aws_iam_role_name

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::414351767826:role/unity-catalog-prod-UCMasterRole-14S5ZJVKOTYTL"
        }
        Action = "sts:AssumeRole"
        Condition = {
          StringEquals = {
            "sts:ExternalId" = "f3230d94-12c6-4e7f-82a3-53ea9f191a35"
          }
        }
      }
    ]
  })

  tags = {
    Name        = "databricks-s3-role"
    ManagedBy   = "Terraform"
    Environment = "dev"
  }
}

# --- IAM Policy granting S3 access to the role ---
resource "aws_iam_role_policy" "databricks_s3" {
  name = "databricks-s3-policy"
  role = aws_iam_role.databricks_role.name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3:GetObject",
          "s3:PutObject",
          "s3:DeleteObject",
          "s3:ListBucket",
          "s3:GetBucketLocation",
          "s3:GetLifecycleConfiguration",
          "s3:PutLifecycleConfiguration"
        ]
        Resource = [
          "arn:aws:s3:::${var.s3_bucket_name}",
          "arn:aws:s3:::${var.s3_bucket_name}/*"
        ]
      }
    ]
  })
}

# --- Databricks Storage Credential ---
resource "databricks_storage_credential" "this" {
  name = "sameer-s3-credential"

  aws_iam_role {
    role_arn = aws_iam_role.databricks_role.arn
  }

  comment = "S3 storage credential for Databricks catalog"

  depends_on = [
    aws_s3_object.catalog_folder,
    aws_iam_role.databricks_role,
    aws_iam_role_policy.databricks_s3
  ]
}

# --- Databricks External Location ---
resource "databricks_external_location" "this" {
  name            = "sameer-s3-location"
  url             = "s3://${var.s3_bucket_name}/databricks-catalog"
  credential_name = databricks_storage_credential.this.name
  comment         = "External location pointing to targetdemo S3 bucket"

  depends_on = [
    databricks_storage_credential.this,
    aws_iam_role_policy.databricks_s3
  ]
}

# --- Databricks Catalog ---
resource "databricks_catalog" "this" {
  name         = "sameer_catalog"
  comment      = "Main catalog managed by Terraform"
  storage_root = "s3://${var.s3_bucket_name}/databricks-catalog"

  properties = {
    purpose     = "development"
    managed_by  = "terraform"
  }

  depends_on = [databricks_external_location.this]
}

# --- Databricks Schema inside the Catalog ---
resource "databricks_schema" "dev" {
  catalog_name = databricks_catalog.this.name
  name         = "sameer_workspace_dev"
  comment      = "Dev schema managed by Terraform"

  properties = {
    environment = "dev"
    managed_by  = "terraform"
  }

  depends_on = [databricks_catalog.this]
}

# --- Outputs ---
output "catalog_name" {
  value       = databricks_catalog.this.name
  description = "Databricks catalog name"
}

output "schema_name" {
  value       = databricks_schema.dev.name
  description = "Databricks schema name"
}

output "external_location_url" {
  value       = databricks_external_location.this.url
  description = "S3 URL used as external location"
}

output "iam_role_arn" {
  value       = aws_iam_role.databricks_role.arn
  description = "IAM role ARN used by Databricks"
}

output "databricks_external_id" {
  value       = databricks_storage_credential.this.aws_iam_role[0].external_id
  description = "External ID generated by Databricks for IAM trust"
}